baseurl = "https://example.com/"
languageCode = "en-US"
title = "it-ninja"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-110542214-1"
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "avatar.jpg"
  author = "Donald Johnson"
  description = "ramblings of a network engineer"
  job_title = "Principal Network Engineer"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "johnsondnz"
  Email         = "donald@it-ninja.xyz"
  Twitter       = ""
  LinkedIn      = "johnsondnz"
  Stackoverflow = ""

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"

[[menu.main]]
  name = "study-notes"
  weight = 100
  identifier = "study-notes"
  url = "/study-notes/"

#[[menu.main]]
#  name = "projects"
#  identifier = "projects"
#  weight = 200
#  url = "/projects/"

#[[menu.main]]
#  name = "resume"
#  identifier = "resume"
#  weight = 300
#  url = "/resume/"
